version: "3.3"

services:
  ldaptive:
    image: maven:3.6.0-jdk-11
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD:/apps/ldaptive
      - ./Ldaptive.java:/apps/ldaptive/Ldaptive.java
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    command: >
      bash -c "cd /apps/ldaptive &&
      javac -cp /root/.m2/repository/io/netty/netty-all/4.1.37.Final/netty-all-4.1.37.Final.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/root/.m2/repository/org/ldaptive/ldaptive/2.0.0-SNAPSHOT/ldaptive-2.0.0-SNAPSHOT.jar:. Ldaptive.java &&
      java -Dhost=ldap://ldap-test:389 -cp /root/.m2/repository/io/netty/netty-all/4.1.37.Final/netty-all-4.1.37.Final.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/root/.m2/repository/org/ldaptive/ldaptive/2.0.0-SNAPSHOT/ldaptive-2.0.0-SNAPSHOT.jar:. Ldaptive"

  ldap-test:
    image: code.vt.edu:5005/middleware/edldap-deploy-env/ldap-test-openldap:latest
    ports:
      - "389:389"
      - "636:636"
      - "88:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11
    logging:
      #driver: "json-file"
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"

  pumba:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12
    depends_on:
      - ldaptive
      - ldap-test
    command: netem --tc-image gaiadocker/iproute2 --duration 20s loss --percent 100 ldaptive_ldap-test_1

networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
